In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("City_zori_uc_sfrcondomfr_sm_sa_month.csv")

In [3]:
display(df)

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,CountyName,2015-01-31,2015-02-28,...,2023-05-31,2023-06-30,2023-07-31,2023-08-31,2023-09-30,2023-10-31,2023-11-30,2023-12-31,2024-01-31,2024-02-29
0,6181,0,New York,city,NY,NY,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,2516.390863,2532.074270,...,3303.045316,3305.204268,3304.044299,3303.820383,3309.824172,3321.923409,3337.701402,3354.988312,3371.478476,3392.834851
1,12447,1,Los Angeles,city,CA,CA,"Los Angeles-Long Beach-Anaheim, CA",Los Angeles County,1851.026558,1862.382360,...,2786.156464,2783.936468,2779.776962,2778.446822,2776.317927,2779.510726,2780.894416,2782.856946,2788.963660,2791.477801
2,39051,2,Houston,city,TX,TX,"Houston-The Woodlands-Sugar Land, TX",Harris County,1200.071815,1201.763926,...,1546.763799,1546.571390,1547.972385,1547.961589,1551.020013,1555.491168,1561.182540,1567.743572,1570.567848,1572.250076
3,17426,3,Chicago,city,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",Cook County,1530.983376,1531.015132,...,2004.602069,2013.826681,2021.305003,2030.420939,2036.658198,2042.221941,2049.448078,2060.720691,2073.437865,2086.636165
4,6915,4,San Antonio,city,TX,TX,"San Antonio-New Braunfels, TX",Bexar County,973.588816,975.396348,...,1404.749280,1401.508611,1397.089617,1397.031326,1396.316124,1398.199217,1398.066707,1397.466639,1394.041111,1392.620914
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3231,6618,20421,Presto,city,PA,PA,"Pittsburgh, PA",Allegheny County,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1657.000000
3232,124999,22469,Lake Hart,city,FL,FL,"Orlando-Kissimmee-Sanford, FL",Orange County,NaN,NaN,...,2482.845983,2465.984543,2448.474470,2442.868752,2432.324087,2425.609585,2425.892668,2438.190138,2425.241607,2431.500000
3233,47500,22678,Sagaponack,city,NY,NY,"New York-Newark-Jersey City, NY-NJ-PA",Suffolk County,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96678.052217,107500.000000
3234,30203,24266,Amagansett,city,NY,NY,"New York-Newark-Jersey City, NY-NJ-PA",Suffolk County,NaN,NaN,...,NaN,NaN,NaN,NaN,74931.568893,66906.441785,68858.272614,72165.585994,77791.659128,75144.416667
3235,47768,26546,South Padre Island,city,TX,TX,"Brownsville-Harlingen, TX",Cameron County,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2350.000000

In [4]:
tx_data = df[df['State'] == 'TX']

In [5]:
display(tx_data)

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,CountyName,2015-01-31,2015-02-28,...,2023-05-31,2023-06-30,2023-07-31,2023-08-31,2023-09-30,2023-10-31,2023-11-30,2023-12-31,2024-01-31,2024-02-29
2,39051,2,Houston,city,TX,TX,"Houston-The Woodlands-Sugar Land, TX",Harris County,1200.071815,1201.763926,...,1546.763799,1546.571390,1547.972385,1547.961589,1551.020013,1555.491168,1561.182540,1567.743572,1570.567848,1572.250076
4,6915,4,San Antonio,city,TX,TX,"San Antonio-New Braunfels, TX",Bexar County,973.588816,975.396348,...,1404.749280,1401.508611,1397.089617,1397.031326,1396.316124,1398.199217,1398.066707,1397.466639,1394.041111,1392.620914
9,38128,9,Dallas,city,TX,TX,"Dallas-Fort Worth-Arlington, TX",Dallas County,1080.733425,1086.338969,...,1705.581198,1694.916395,1689.450140,1689.258107,1692.513942,1701.121975,1704.075402,1708.206896,1708.551038,1709.807306
10,10221,10,Austin,city,TX,TX,"Austin-Round Rock-Georgetown, TX",Travis County,1181.954801,1187.985744,...,1759.814202,1744.435090,1734.160451,1726.330833,1721.566892,1722.491439,1725.281147,1726.529973,1724.319689,1719.293768
15,18172,15,Fort Worth,city,TX,TX,"Dallas-Fort Worth-Arlington, TX",Tarrant County,1047.684390,1052.655785,...,1674.274401,1672.435786,1671.190123,1670.081755,1672.852082,1678.668352,1681.947801,1682.146701,1679.387643,1677.156930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3201,18809,11224,Kemah,city,TX,TX,"Houston-The Woodlands-Sugar Land, TX",Galveston County,NaN,NaN,...,1431.345289,1406.709097,1368.927240,1373.112871,1375.239176,1355.796887,1380.298861,1371.807133,1437.588923,1441.222222
3205,20303,11740,Saint Hedwig,city,TX,TX,"San Antonio-New Braunfels, TX",Bexar County,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1858.745830,NaN,1879.228157,1911.000000
3211,47663,12330,Shenandoah,city,TX,TX,"Houston-The Woodlands-Sugar Land, TX",Montgomery County,NaN,NaN,...,NaN,NaN,1527.650407,1556.487909,1624.968413,NaN,1788.678409,1860.282622,1894.209917,2005.555556
3215,34186,13375,Sunset Valley,city,TX,TX,"Austin-Round Rock-Georgetown, TX",Travis County,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1619.250000
3235,47768,26546,South Padre Island,city,TX,TX,"Brownsville-Harlingen, TX",Cameron County,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2350.000000

In [6]:
column_names = tx_data.columns.tolist()
print(column_names)

['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName', 'State', 'Metro', 'CountyName', '2015-01-31', '2015-02-28', '2015-03-31', '2015-04-30', '2015-05-31', '2015-06-30', '2015-07-31', '2015-08-31', '2015-09-30', '2015-10-31', '2015-11-30', '2015-12-31', '2016-01-31', '2016-02-29', '2016-03-31', '2016-04-30', '2016-05-31', '2016-06-30', '2016-07-31', '2016-08-31', '2016-09-30', '2016-10-31', '2016-11-30', '2016-12-31', '2017-01-31', '2017-02-28', '2017-03-31', '2017-04-30', '2017-05-31', '2017-06-30', '2017-07-31', '2017-08-31', '2017-09-30', '2017-10-31', '2017-11-30', '2017-12-31', '2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30', '2018-05-31', '2018-06-30', '2018-07-31', '2018-08-31', '2018-09-30', '2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30', '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31', '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31', '2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30', '2020-05-31', '2020-06-30', '2020-07-31', '2020-08-31', '2020-09-30', '2020-10-31', '2020-11-30', '2020-12-31', '2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30', '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31', '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31', '2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30', '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31', '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31', '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30', '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31', '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31', '2024-01-31', '2024-02-29']

In [9]:
index_2020_01_31 = column_names.index('2020-01-31')
selected_columns = column_names[:8] + column_names[index_2020_01_31:]
filteredrental = tx_data[selected_columns]

In [10]:
display(filteredrental)

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,CountyName,2020-01-31,2020-02-29,...,2023-05-31,2023-06-30,2023-07-31,2023-08-31,2023-09-30,2023-10-31,2023-11-30,2023-12-31,2024-01-31,2024-02-29
2,39051,2,Houston,city,TX,TX,"Houston-The Woodlands-Sugar Land, TX",Harris County,1319.159758,1325.291645,...,1546.763799,1546.571390,1547.972385,1547.961589,1551.020013,1555.491168,1561.182540,1567.743572,1570.567848,1572.250076
4,6915,4,San Antonio,city,TX,TX,"San Antonio-New Braunfels, TX",Bexar County,1151.148727,1154.890101,...,1404.749280,1401.508611,1397.089617,1397.031326,1396.316124,1398.199217,1398.066707,1397.466639,1394.041111,1392.620914
9,38128,9,Dallas,city,TX,TX,"Dallas-Fort Worth-Arlington, TX",Dallas County,1360.713573,1361.234266,...,1705.581198,1694.916395,1689.450140,1689.258107,1692.513942,1701.121975,1704.075402,1708.206896,1708.551038,1709.807306
10,10221,10,Austin,city,TX,TX,"Austin-Round Rock-Georgetown, TX",Travis County,1414.446645,1419.241049,...,1759.814202,1744.435090,1734.160451,1726.330833,1721.566892,1722.491439,1725.281147,1726.529973,1724.319689,1719.293768
15,18172,15,Fort Worth,city,TX,TX,"Dallas-Fort Worth-Arlington, TX",Tarrant County,1317.022917,1327.468846,...,1674.274401,1672.435786,1671.190123,1670.081755,1672.852082,1678.668352,1681.947801,1682.146701,1679.387643,1677.156930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3201,18809,11224,Kemah,city,TX,TX,"Houston-The Woodlands-Sugar Land, TX",Galveston County,NaN,NaN,...,1431.345289,1406.709097,1368.927240,1373.112871,1375.239176,1355.796887,1380.298861,1371.807133,1437.588923,1441.222222
3205,20303,11740,Saint Hedwig,city,TX,TX,"San Antonio-New Braunfels, TX",Bexar County,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1858.745830,NaN,1879.228157,1911.000000
3211,47663,12330,Shenandoah,city,TX,TX,"Houston-The Woodlands-Sugar Land, TX",Montgomery County,NaN,NaN,...,NaN,NaN,1527.650407,1556.487909,1624.968413,NaN,1788.678409,1860.282622,1894.209917,2005.555556
3215,34186,13375,Sunset Valley,city,TX,TX,"Austin-Round Rock-Georgetown, TX",Travis County,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1619.250000
3235,47768,26546,South Padre Island,city,TX,TX,"Brownsville-Harlingen, TX",Cameron County,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2350.000000

In [11]:
filteredrental.to_csv("tx_rental_filtered.csv", index=False)